aircraft_model: NARROW_BODY_JET
charges_file_path: data/graph/LEMD_EGLL_2023_04_01_charges.npy
climb_phase_switch_allowance_climb_time_bins: 10
cost_model_beta0: 0.0
cost_model_beta1: 2.0
cost_model_beta2: 0.0
cost_model_beta3: 1.0
cruise_altitude_ft: 35000.0
cruise_speed_kts: 450.0
delta_t_seconds: 600
device_preference: cuda
distances_file_path: data/graph/LEMD_EGLL_2023_04_01_distances.npy
etto_delta_t_seconds: 30
file_prefix: LEMD_EGLL_2023_04_01
goal_elevation_ft: 0.0
goal_node: EGLL
graph_file_path: data/graph/LEMD_EGLL_2023_04_01.gml
initial_alt_ft: 0.0
max_elapsed_time_since_takeoff_hours: 0.75
max_flight_duration_hours: 5.0
origin_node: LEMD
output_dir: data/graph/transitions
source_elevation_ft: 0.0
wind_data_dir: D:\\project-equinox\\data\\era5
disable_config_wind_model: true
gamma: 0.001
alpha_pref_reg: 1.0